{% set name = "polyscope" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e7452f52c48bbef831af11e5faecdf16447e79d39d3685e85277dcaf63401dfc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --install-option="--exclude-arch"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
  host:
    - python
    - pip
    - xorg-libxfixes  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxinerama  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxi  # [linux]
  run:
    - python
    - numpy
    - xorg-libx11  # [linux]

test:
  imports:
    - polyscope

  # Could run more serious test like this, but the polyscope-py MANIFEST 
  # currently does not include this test script.
  #commands:
    #- python test/polyscope_test.py backend=openGL_mock

about:
  home: https://polyscope.run
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Polyscope: A viewer and user interface for 3D data (python bindings)'
  doc_url: https://polyscope.run
  dev_url: https://github.com/nmwsharp/polyscope-py

extra:
  recipe-maintainers:
    - nmwsharp
