{% set name = "polyscope" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 30e0c078cea3f258459c11ade5c1d1c1cd2f7ffe2de5f4087fc6cf592b656c05

build:
  number: 0
  script:
    - {{ PYTHON }} setup.py bdist_wheel --exclude-arch
    - {{ PYTHON }} -m pip install -f dist polyscope=={{ version }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
  host:
    - python
    - pip
    - xorg-libxfixes  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxinerama  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxi  # [linux]
  run:
    - python
    - numpy
    - xorg-libx11  # [linux]

test:
  imports:
    - polyscope

  # Could run more serious test like this, but the polyscope-py MANIFEST 
  # currently does not include this test script.
  #commands:
    #- python test/polyscope_test.py backend=openGL_mock

about:
  home: https://polyscope.run
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Polyscope: A viewer and user interface for 3D data (python bindings)'
  doc_url: https://polyscope.run
  dev_url: https://github.com/nmwsharp/polyscope-py

extra:
  recipe-maintainers:
    - nmwsharp
