{% set name = "polyscope" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ucb93b11ef0ac8c76e92d0a5f655.dl.dropboxusercontent.com/cd/0/get/BGh_o-Bu31qcJv55Hts6TJ_nu2TE2ShV9VlU0pxewmV7z0nP3LRej8_mi8Ntt9Zr6SRW56wmSz5e5Y7Oqu1Sz3LnhkTYzPNvu95xHRehJd4zyTEvvy7cTgWxhuN20EwQC-k/file#
  sha256: 172a9fe3e97bcfa083a2a3f0325226e34d849c41dfd2c2f85dcd0fa08cf0a761

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --install-option="--exclude-arch"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.1
    - make
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
  host:
    - python
    - pip
    - xorg-libxfixes  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxinerama  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxi  # [linux]
  run:
    - python
    - numpy
    - xorg-libx11  # [linux]

test:
  imports:
    - polyscope

  # Could run more serious test like this, but the polyscope-py MANIFEST 
  # currently does not include this test script.
  #commands:
    #- python test/polyscope_test.py backend=openGL_mock

about:
  home: https://polyscope.run
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Polyscope: A viewer and user interface for 3D data (python bindings)'
  doc_url: https://polyscope.run
  dev_url: https://github.com/nmwsharp/polyscope-py

extra:
  recipe-maintainers:
    - nmwsharp
